wandb_version: 1

epochs:
  desc: null
  value: 30
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.01
model:
  desc: null
  value: C3D
dataset:
  desc: null
  value: Binary
optimizer:
  desc: null
  value: SGD
load_model:
  desc: null
  value: true
load_weights_path:
  desc: null
  value: ../../weights/C3D/model_29.pth
save_weights_path:
  desc: null
  value: ../../weights/C3D_v1/
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710346679.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
